### ISSUE TITLE
How-To Review

### ISSUE THREAD

**Issue by droumis** [holoviz/panel#4444]
We have completed the initial migration/reworking of User Guide content primarily into How-to guides in an effort to begin restructuring docs more directly around the needs of our users (à la [Diataxis](https://diataxis.fr/)). In the case of How-to's, that need is solving a specific real-world problem. Now, a bunch of the How-to material has to be cleaned up and made consistent. 

Here are the key guidelines for a How-to guide:
1. Succinct title that could be prefixed with 'How to..'
2. Clearly and succinctly describe what it aims to solve
3. Provide a sequence of actions to solve one real problem
4. Exclude teaching and discussion
5. Follow a consistent format
6. Refer to relevant resources

Here is my specific proposal for How-to guide schema that I will begin to align our pages on:

---

`# Succinct title that could have been prefixed with 'How to..'`

One sentence or so that clearly and succinctly describes what this guide aims to solve ("This guide addresses how to...")

> An *optional* ordered prerequisites admonition
> 1. This facilitates a required ramp-up and reduces content duplication.
For example: 
<img width="781" alt="image" src="https://user-images.githubusercontent.com/6613202/218503944-9cc6a48e-0b63-46ae-9e49-b3a761b43275.png">

```---```

Content: How-to guides are task-oriented, assume familiarity with the basics, and are intended for users when they are in the midst of working, i.e. when succinctness and clarity are paramount. Therefore, add content here that provides a sequence of actions to solve one real problem. Use brief clarifying text (such as what would help experienced cooks follow a recipe correctly), but exclude teaching and discussion (such as what would help a student acquire basic competence in a culinary curriculum). If you feel like an educational explanation is required, ensure that such content is present in a Tutorial or Background page and link to it. See [this page](https://diataxis.fr/tutorials-how-to/#tutorials-how-to) for more on the distinction between How-to guides and the more learning-oriented Tutorials.

It's ok to branch out on guidance for alternate approaches, but include brief justification: *In the case of …, an alternative approach is to…*.

Mention any common real-world gotcha's and provide guidance on how to deal with it.

Reference the reference guides for a complete list of options.

When possible, include a complete copyable code block/recipe; e.g. "Here is the complete code for this subsection in case you want to easily copy it:" or "Putting it all together:"

```---``` 

`## Related Resources`
- List relevant resources from any other section in the docs.
---

**Comment by philippjfr** [comment]
Addresses #4444 

# TODO:
## General
- [x] Reorganize the highest level of How-to as to not mix thematic/topic-based sectioning with difficulty-based sectioning (e.g. having both an 'Exporting and Saving Output' section and 'Advanced' section on the same level. Currently on hold as there is still some [consensus to be sought](https://github.com/holoviz/panel/pull/4412#discussion_r1097899169) on this issue. update.. [new organization](https://hackmd.io/@holoviz/minutes#2023-02-15-HoloViz-Docs-Meeting) proposed and agreed upon.
- [ ] Review section and subsection card phrasing for consistency
- [ ] Review card octicons for accuracy and discriminability 
- [ ] Why don't horizontal lines appear in the docs with `---`?
- [ ] Do all how to page titles match their card titles?
- [x] add components/index to the how to index toctree
- [ ] review TOC's

## Basics
### Choose an API:
- [x] This subsection is very important but it is broad and teaching-oriented and therefore it fits much better in the Background. If there are certain aspects of this material that are crucial for all Panel users to learn, then we should incorporate them into the Getting Started Guide (either Core Concepts or expand/create an additional Tutorial).
- [x] List Param guides before Links in the index
- [ ] Add a subsection about "Building UIs with the Reactive API"

### Create Components
#### Initialize Components
- [x] add toctree to index 

Construct Panes, Access Pane Type, Access Widget Values
  - [x] Add problem statement
  - [x] replace See Also admonition with Related  Resources

Add or Remove Components
  - [x] Reduce size of 'some text' markdown in app example
  - [x] add complete copyable block of code at the end of subsections
  - [x] Fix warning about `background`
  - [x] Add problem statement
  - [x] replace See Also admonition with Related  
  - [x] Add link to GridSpec reference gallery


#### Style Components

Apply CSS
  - [x] Add problem statement
  - [x] Add related resources
  - [x] Add a complete copyable block at the end 
  - [ ] Add resource link to 'Apply Templates' How-to's

Change Background
  - [x] Remove this how-to since `background` is now just another parameter, instead of having to explain the `styles` dict handling

Customize Loading Icon, Control Visibility
  - [x] Fix warning about `background`
  - [x] Add problem statement
  - [x] Add related resources


#### Arrange and Size Components

Customize Spacing, Align Components, Control Size
  - [x] Fix warning about `background`
  - [x] Add problem statement
  - [x] Add related resources


### Declare UIs with parameters
- [x] Edit title to include 'Param' and 'API', e.g. "Declare UIs with the Param API"
- [x] Capitalize all references to Param's "Parameters" or "Parameterized" objects
- [x] Fix bad link to 'Declare Parameter dependencies'
- [ ] Add octicons for each guide card

Building UIs using Param
- [x] change title to "Generate widgets from `Parameters`."
- [x] Add related resources
- [x] Include link to background page on Param API
- [x] Fix `WARNING:param: Setting non-Parameter class attribute BaseClass.int_list = [1, 7] `
- [x] Add problem statement
- [x] Add prerequisite on Param docs
- [x] File issue about multifileselect spacing

Declare Custom Widgets
- [x] Replace text mentions about 'previous sections' with prerequisites
- [x] Add label to first subsection
- [x] Add related resources
- [x] Add problem statement
- [x] Add prerequisite on How to > Building UIs using Param

Declare Parameter Dependencies
- [x] Add related resources
- [x] Add problem statement
- [ ] Rewrite to make it more task-oriented
- [x] Add prerequisite on How to > Building UIs using Param

Param Subobjects
- [x] Make title into how to ...
- [x] Add prerequisites on How to > Building UIs using Param
- [x] Add prerequisites on How to > Declare Parameter Dependencies
- [x] Add related resources
- [x] Add problem statement

### Link Parameters
- [x] edit title to reflect that this is related to the Callbacks API: e.g. "Link parameters with the Callbacks API"
- [x] remove reference to another section in the intro text; revise
- [ ] Add octicons for each guide card
- [ ] The dissociation of .jslink, js_on_click, and jscallback is not clear enough.. need to reorganize/rewrite these JS how-to's

Watchers
- [x] make title in to how to...
- [x] remove reference to 'previous' guide
- [x] Add related resources
- [x] Add problem statement
- [x] change references of `param.watch` to `.watch`
- [x] remove reference to subsequent guide sections
- [ ] revise into how-to recipes (and potentially some Background)
- [x] Add prerequisites on How to > .link guide

Links in Python
- [x] Add related resources
- [x] Add problem statement

Links in Javascript
- [x] Remove references to 'link example above' and artifacts like that
- [x] Add related resources
- [x] Add problem statement
- [x] Add link to linking plots with jslinks
- [x] Make title into how to...
- [x] change pyviz to holoviz in URL example
- [ ] Move URL example on js_on_click to the javascript callbacks how-to

Link plots in Javascript
- [x] fix wrong link to guide
- [x] Add related resources
- [x] Add problem statement
- [x] Add prerequisite for other jslink page
- [x] make title into how to ...

Javascript callbacks
- [x] Add related resources
- [x] Add problem statement
- [x] make title into how to ...
- [x] distinguish title from 'links in javascript' how to

### Interact with Functions
- [x] edit title to reflect that this is related to the Interact API: e.g. "Build UIs with the Interact API"
- [x] fix octicons for each guide card

Generate Widgets for Function Arguments 
- [ ] add link to reference
- [x] fix use of `style = ...background`
- [x] Add 'let's put it all together:' at end

Customize Layout with Interact
- [ ] add link to reference
- [x] add prerequisite for 'generate widgets with interact..'

Fix Values with Interact
- [ ] add link to reference
- [x] add prerequisite for 'generate widgets with interact..'

Disable Continuous Updates with Interact
- [ ] add link to reference
- [x] add prerequisite for 'generate widgets with interact..'

### Apply Templates
Set a Template
Arrange Components in a Template
- [x] add prerequisite for setting a template

Toggle Modal
- [x] add prerequisite for setting a template

Customize Template Theme
- [x] add prerequisite for setting a template

Build a Custom Template
- [x] add a heading for the first section
- [x] add prerequisite for setting a template
- [x] add prerequisite for customizing a template theme

### Build a Pipline
- [x] make section card text 'how to ...'
- [x] Remove 'initialize components' heading from subsection index

Create a Pipeline
- [x] Add complete copyable code block

Create a Non-Linear Pipeline
- [x] Add complete copyable code block

Customize Pipeline Layout
Control Pipeline Flow
- [x] Add complete copyable code block

###  Build Custom Components
- [x] make section text consistent in style with others
- [ ] Make the how-to's more recipe-like, and the background more explanation.. right now there is a lot of overlap

Combine Existing Components
- [x] remove rogue parentheses 

Build Components from Scratch
- [x] make the associated background page a prerequisite
- [x] Fix link to background > external dependencies

## Display and Export
- [x] redistribute section into build and share sections

### Display Components and Apps
- [x] Move into Build Apps section

Display Output in Notebooks
- [x] Add problem statement
- [x] Add related resources

Develop Apps in an Editor
- [ ] needs to be written

Develop Apps in JupyterLab
- [x] rename to 'Preview apps in jupyterlab'
- [ ] needs to be written

## Improve Performance
- [ ] make octicons different
### Register Session Callbacks
- [x] Add problem statement for all guides
- [x] Add related resources heading for all guides

Asynchronous Callbacks
- [x] rename to how to ... format
- [x] add warning admonition for the python version
- [ ] fix "ModuleNotFoundError: No module named 'aiohttp'" when rerunning the pyodide extension

Load Callbacks
- [x] fix bad link
- [ ] fix bad grammar

### Access Session State
### Cache Data
### Improve Performance
### Improve Scalability
### Enable Profiling and Debugging
### Set up testing for an application

## Server Configuration and deployment
### Configure the server
### Integrate with other Servers
### Deploy Applications
### Add Authentication
### Export and Save Output
- [x] Add cards to the index for individual pages
- [x] rename to how to.. 
- [x] Move to new "share" section that generalized 'Deploy and Export;

Embedding State
- [x] rename to how to..
- [x] Add problem statement
- [x] Add related resources

Saving
- [x] rename to how to..
- [x] Add problem statement
- [x] Add related resources

Bokeh
- [x] rename to how to..
- [x] Add problem statement
- [x] Add related resources

### Run Panel in WebAssembly
