### ISSUE TITLE
Release checklist for Version 1.0

### ISSUE THREAD

**Issue by philippjfr** [holoviz/panel#4695]
- [ ] JupyterLite
  - [ ] Ensure automated test by Marc can run successfully such that the right top cells (green/ red) can be set. [Marc, need help from @philippjfr to get started due to major refactor]
  - [x] #4530 [Marc]
  - [x] Ensure all examples run (or have banner warning of issues) [Marc]
  - [x] Add links throughout documentation
    - [x] Component gallery
    - [x] App Gallery
    - [x] How-to guides
- [x] Gallery
  - [x] Re-run every example and fix any remaining issues
  - [x] Fix links (currently each card adds a link to the source notebook but since the entire card is clickable you can't navigate there)
- [ ] Documentation
  - [x] Fix Styling Issues #4647
  - [x] Reorganize Navigation #4681
  - [x] Ensure homepage not outdated #4214 
  - [x] Ensure all pages can be run in pyodide
  - [x] Ensure 1.0 api is used and not some older api. For example pn.bind, pn.state.served (@maximlt )
  - [x] Migration guide complete
  - [ ] Getting Started
    - [ ] Updated 2-minute getting started
    - [ ] Rewrite build-an-app guide based on latest reactive APIs
  - How-to
    - Prepare to develop
      - [x] how_to/display
        - [x] JupyterLab Preview (@maximlt)
        - [x] Break this out into notebook and editor/IDE sections (@droumis)
      - [x] how_to/apis (@droumis)
        - [x] Move this to background
    - Build Apps
        - [x] how_to/interactivity (@Hoxbro)
          - [x] Rename how_to/reactive to how_to/interactivity and make it third item in Build Apps section
          - [x] Add section on pn.bind as component (put param docs in "Related Resources")
          - [x] Add section on binding parameters and bound function on components `pn.pane.Markdown(pn.bind(...))` 
          - [x] Add section on binding `hvplot.interactive` (if you need inspiration look at Portfolio Optimizer)
        - [x] Remove how_to/interact (@droumis )
        - [x] how_to/templates/ (@maximlt)
          - [x] Move this up from "Prepare to share" 
          - [x] Update screenshots
    - Create specialized UIs (Rename this to something like "Specialized UIs and APIs")
      - how_to/links (move this here) (@droumis )
      - how_to/param (move this here)  (@droumis )
      - Find way to add multi-page app guide
    - Prepare to share
      - [ ] how_to/performance
        - [ ] defer_load (@philippjfr)
        - [x] `--reuse-sessions` (@philippjfr)
      - [ ] how_to/concurrency/load_balancing (@maximlt)
  - [x] Component gallery
    - [x] Review template notebook (@maximlt)
    - [x] Quick run through of all pages to discover warnings
  - [x] App gallery
    - [x] Figure out how to link to deployed dev and prod gallery depending on build
    - [x] Add external examples (e.g. awesome-panel.org and @sophiamyang's apps)
  - [x] Ensure all pages can be run in pyodide
- [x] Bug fixes
  - [x] Panel extension and resource loading
    - [x] JupyterLab 4 (does it still work?) 
  - [ ] Styling
    - [ ] Fix issues with scrollbars being unstyled inside shadow DOM
    - [x] Fix Fenced Codeblock style issue #4698
    - [x] Fix various FastTemplate issues https://github.com/holoviz/panel/issues/4727
  - [x] IPyWidgets
    - [x] Figure out if ipywidgets_bokeh can be made to work before 1.0 release 
- [ ] Build infrastructure
  - [ ] Ensure that all build tooling is available on defaults (either by postponing hatch or by ensuring hatch(-conda) is available)
  - [ ] Decide whether completing and merging hatch PR is feasible

**Comment by MarcSkovMadsen** [comment]
[] Reorganize top level navigation (as done in not approved new-homepag PR)
- [] Rename Reference Gallery to Component Gallery
- [] Rename Gallery to App Gallery and move after Component Gallery
- [] Rename Background to Explanation
- [] In the cards use the titles "Getting Started", "How-to", "Explanation" and "Reference API"
[] Use improved demo app from not approved new-homepage PR. Revert colors back to acceptable color scheme.
[] Jupyterlite: Ensure automated test by Marc can run successfully such that the right top cells (green/ red) can be set.
[] Migration Guide
[] Sufficient time for users to test RC releases.

# Nice to have

Go through all dokumentation to make sure the recommend 1.0 api is used and not some older api. For example pn.bind, pn.state.is_served etc.

**Comment by philippjfr** [comment]
Closing, the majority of this was done. The rest will be done subsequently.
