### ISSUE TITLE
Chat Docs issues

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#5622]
As the new chat interface is in the `dev` docs I will start reviewing and add issues here

Dev Docs: https://holoviz-dev.github.io/panel/reference/index.html#widgets

## Issues

- [x] Spelling errors in Chat component gallery thumbnails. I've updated the ones in [post below](https://github.com/holoviz/panel/issues/5622#issuecomment-1760088855). Philipp should upload to CDN.
- [x] Component Gallery now has many categories without clear ordering. To be fixed by #5692
- [x] No mention of and link to panel-chat-examples.
  - [x] Should be in App Gallery https://holoviz-dev.github.io/panel/gallery/index.html. To be fixed by #5690 
  - [x] Should be in ChatInterface reference guide. Could be in ChatEntry and ChatFeed guides
- [x] Images missing from component gallery
- [x] Cannot run dev examples in Pyodide (We now can but with issues listed below)
- [x] #5625

### ChatMessage

- [x] Design specification image not found
  - [x] Remember to change ChatEntry to ChatMessage
- [x] Cannot import name `document` from `js` error when running Matplotlib in pyodide. See https://github.com/pyodide/pyodide/issues/561. To be worked around via #5702.
- [ ] "Reference ... isn't known" in console when running in Pyodide.
- [x] Beat boxing cannot play. To be fixed by #5688.
- [x] Both Streamlit and LangChain has the concept of message(s). For example `st.chat_message`. Consider if `ChatMessage` is a better name than `ChatEntry` @ahuang11 .

### ChatFeed

- [x] Design specification image not found
- [x] Verbose mentioned but not set. To be fixed by #5691 
- [x] Feed without entries is totally flat (Is not an issue, but a feature).
- [x] Await outside function

### ChatInterface

- [x] Design specification image not found
- [x] #5695. To be solved by #5701
- [x] #5708. To be solved by #5712
- [x] #5705. To be solved by #5706
- [x] #5709
- [x] #5716
- [x] `callback_user` not described in Parameters section.
- [x] ChatInterface Perspective examples not working. To be fixed by #5696.
- [x] The TextInput widget does not stretch when `show_button_name=False`. Fixed by #5697
- [x] show_button_name not working

### PanelCallbackHandler

- [x] Images not showing
- [x] #5707. Fixed by #5710
- [x] No reference guide
- [x] #5629
- [x] Remaining issues to be solved by https://github.com/holoviz/panel/pull/5682.

### ChatBox

- [x] No deprecation alert at top of reference notebook. To be solved by #5689.
- [x] Not deprecated

### Streamlit migration guide

- [x] Card issue in index file. To be fixed by #5685
- [x] To be solved by #5670

## Card issue in index file

https://holoviz-dev.github.io/panel/how_to/streamlit_migration/index.html

![image](https://github.com/holoviz/panel/assets/42288570/2b21d631-6aaa-4e6b-b016-e7eb0d3ece51)

## Images missing from component gallery

![panel-docs](https://github.com/holoviz/panel/assets/42288570/307dc036-fb55-483c-a842-159b5773900b)

## Cannot run dev examples in Pyodide

The problem is that the bokeh js cannot be found. I.e. we cannot test if dev docs works and makes sense.

![image](https://github.com/holoviz/panel/assets/42288570/94ec9454-9975-4c35-ab9b-41ca4d065488)

## Design Specification image not found

https://holoviz-dev.github.io/panel/reference/widgets/ChatEntry.html

![image](https://github.com/holoviz/panel/assets/42288570/8f6c3e01-6d43-4864-9272-2009c8b3919c)

## Beat boxing cannot play

![image](https://github.com/holoviz/panel/assets/42288570/6e8ada35-ac70-446e-9f28-e7c5d516891c)

On my mobile it says "fejl" which is danish for "error"

![image](https://github.com/holoviz/panel/assets/42288570/c41d33a4-daa9-49fd-8499-ef0807616133)

### Feed without entries is totally flat

This might confuse users

https://holoviz-dev.github.io/panel/reference/widgets/ChatFeed.html#id2

![image](https://github.com/holoviz/panel/assets/42288570/334a67ea-9a41-44bc-81b0-5632051f7685)

## Await outside function

![image](https://github.com/holoviz/panel/assets/42288570/5afcba9c-27e5-465a-8b44-af7c257b52b2)

## show_button_name not working

I would expect the buttons to have icons but no text.

![image](https://github.com/holoviz/panel/assets/42288570/20e0d04e-35e7-4444-a736-0bd8165d1df0)

## Images not showing

![image](https://github.com/holoviz/panel/assets/42288570/48986f75-d68e-4a28-b427-6f73b6fe832a)

## Component Gallery now has many categories without clear ordering.

![image](https://github.com/holoviz/panel/assets/42288570/68988497-1984-4737-9d76-37b843e4be8f)

## Verbose mentioned but not set

In the ChatFeed Reference notebook

![image](https://github.com/holoviz/panel/assets/42288570/9fb5b966-7791-4d48-a1a3-f7588dffff19)

**Comment by Hoxbro** [comment]
Do you have the images you want for the gallery?

The second problem is related to the latest Bokeh release, which is unavailable on all channels. My feeling is this will fix itself given time.

**Comment by MarcSkovMadsen** [comment]
For the second problem I think the cause is that custom wheels are not published for alpha, beta and release candidates via the pipeline.

![image](https://github.com/holoviz/panel/assets/42288570/55e59d85-fe59-49d4-ac36-35cc06996803)

**Comment by philippjfr** [comment]
They are published but we only publish the latest bokeh version (i.e. 3.3.0 now). Seems like the website was still built with bokeh 3.2.2 for some reason.

**Comment by MarcSkovMadsen** [comment]
You can for example use these pictures @philippjfr 

![test-finished-1](https://github.com/holoviz/panel/assets/42288570/36a1bf37-392a-4220-ba65-07331d69710c)

![test-finished-1](https://github.com/holoviz/panel/assets/42288570/ee6c9dd6-077e-4e95-ae17-62117a2db7cc)

![test-finished-1](https://github.com/holoviz/panel/assets/42288570/dddbeb6f-1fec-4e09-a8c1-c2c1e81b7582)

You can finetune via the below

```python
import time

import panel as pn
import pytest
from panel.widgets import ChatEntry, ChatFeed, ChatInterface

VIEWPORT = {"width": 500, "height": 500}  # Optimal for Twitter
PORT = 5007
URL = f"http://localhost:{PORT}"

def run(page, component, zoom):
    server = pn.serve(component, port=PORT, threaded=True, show=False)
    time.sleep(0.2)
    page.goto(URL)
    page.locator("body").evaluate(f"(sel)=>{{sel.style.zoom = {zoom}}}")
    time.sleep(4)
    server.stop()

@pytest.mark.browser_context_args(
    viewport=VIEWPORT
)
def test_chat_entry(page):
    component = pn.Column(
        ChatEntry(value="How my I help?", user="Assistant"),
    )
    run(page, component, 1.25)

@pytest.mark.browser_context_args(
    viewport=VIEWPORT
)
def test_chat_feed(page):
    component = ChatFeed()
    component.send("How my I help?", user="Assistant")
    component.send("You can answer my questions.", user="User")
    run(page, component, 1.25)

@pytest.mark.browser_context_args(
    viewport=VIEWPORT
)
def test_chat_interface(page):
    component = pn.Column(ChatInterface(margin=0), margin=10)
    component[0].send("How my I help?", user="Assistant")
    component[0].send("You can answer my questions.", user="User")
    run(page, component, 1.25)
```

```bash
pytest script.py --headed --screenshot on
```

**Comment by ahuang11** [comment]
This fixes show_button_name
https://github.com/holoviz/panel/pull/5652

**Comment by MarcSkovMadsen** [comment]
## Cannot import name `document` from `js`

Seem the `ChatMessage` docs can now run in pyodide. But then a new issue appears.

![image](https://github.com/holoviz/panel/assets/42288570/dd46dd52-db6d-4146-935b-c113c0a96723)

**Comment by MarcSkovMadsen** [comment]
## ChatInterface FileUpload example not working

When I try the upload on the `dev` site using pyodide it does not work. I don't see anything displayed. And don't see the cause in the browser console either.

![image](https://github.com/holoviz/panel/assets/42288570/2c307b21-3469-48b7-8d09-2d459e0562bf)

**Comment by MarcSkovMadsen** [comment]
## The TextInput does not stretch when show_button_name=False

![image](https://github.com/holoviz/panel/assets/42288570/7225ef86-b28e-4d5e-b51b-b0523fc14990)

Is this a bug or a feature @ahuang11 ?

**Comment by ahuang11** [comment]
I think this can be closed? If not please open new issues with remaining issues.
