### ISSUE TITLE
Finalize Tutorials for Panel 1.4

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#6390]
This issue keeps track of outstanding issues before Tutorials are ready for Panel 1.4 release.

## Todo

- [ ] Write React to User input (pn_bind.md) tutorial (Philipp)
- [ ] Handle State (state.md) tutorial (Philipp)
  - [ ] Rename to Use State
- [ ] Update Todo App Code (Philipp) and explain the code
- [ ] Update Image Classifier App Code (Philipp) and explain the code
- [ ] Get `{pyodide}` code blocks to render output when build and interactive when run (Philipp).
- [ ] Improve Streaming Dashboard (build_streaming_dashboard.md) to be consistent with other tutorials.
- [ ] Convert (tutorial) mp4 videos to iphone compatible mp4 videos

## Nice to Have

- [ ] Update Class-Based Approach (param.md)
  - [ ] List selected parts of Param user guide as *prerequisites*
- [ ] Update Interactivity (Intermediate) (interactivity)
- [ ] Add Toc Tree to Intermediate Tutorials
- [ ] Review and update the Intermediate and Experienced index.md files
