### ISSUE TITLE
Docs issues to be fixed before 1.5.0

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/panel#7126]
I will start reviewing the docs via https://holoviz-dev.github.io/panel.

I will use this issue to list things I can't or should not fix.

I will fix a lot of other things in https://github.com/holoviz/panel/pull/7127.

# Todo (not for me)

**The issues below are explained in more depth in comments below!**

- [x] 0. Create a 1.5.0 Change Log to make it easier to test changed docs. Done in https://github.com/holoviz/panel/pull/7136
- [x] 1. Move `Custom_Components` to bottom of index
- [x] 2. Add Missing Images to Component Gallery.
- [x] 3. Review and merge PRs
  - [x] https://github.com/holoviz/panel/pull/7043
  - [x] https://github.com/holoviz/panel/pull/7279
  - [x] https://github.com/holoviz/panel/pull/7183
  - [x] https://github.com/holoviz/panel/pull/7051
  - [x] https://github.com/holoviz/panel/pull/7088
  - [x] https://github.com/holoviz/panel/pull/7029
- [ ] 4. Add missing logo_horizontal_light_theme.png
- [x] 5. Navigate to Custom Components when clicking `Custom_Components`.
- [x] 6. Make Pyodide code blocks work (importShim is not defined, unsupported in polyfill mode)
- [x] 7. Consider enabling `pn.custom.AnyWidgetComponent` usage
- [ ] 8. Document how to not sync JSComponent parameters
- [x] 9. Support css sharing between `AnyWidget` and `AnyWidgetComponent`
- [ ] 10. Update `AnyWidget` *efficiency* comment.
- [x] 11. Review https://holoviz-dev.github.io/panel/how_to/migrate/anywidget/index.html
- [x] 12. Fix document did not publish any contents
- [x] 13. Add missing styles to Material UI example
- [x] 14. Fix errors and exceptions in docs build logs.
- [x] 15. `DiscretePlayer` broken
- [x] 16. Finalize Chat layout change
- [x] 17. Add missing `FileDropper` thumbnail
- [x] 18. Enable Marc to create PY.CAFE Panel user and migrate examples to that user
- [x] 19. Add missing Placeholder thumbnail.
- [ ] 20. Deprecate fastapi embed guide
- [ ] 21. Update custom components explanation

**Comment by MarcSkovMadsen** [comment]
## 1. Move `Custom_Components` to bottom of index

![image](https://github.com/user-attachments/assets/6a2a92c9-1259-42d6-bb63-02990f447b3a)

**Comment by MarcSkovMadsen** [comment]
## 2. Add Missing Images to Component Gallery.

![image](https://github.com/user-attachments/assets/467d4bd4-7354-494c-81ab-52233350fb2a)

**Comment by MarcSkovMadsen** [comment]
## 4. Add missing logo_horizontal_light_theme.png

![image](https://github.com/user-attachments/assets/2b708044-0aa8-4440-ba0e-62a8e8154029)

**Comment by MarcSkovMadsen** [comment]
## 5. Navigate to Custom Components when clicking Custom_Components.

When I click the `Custom_Components` link I don't navigate to it. Instead the Component Gallery reloads.

![image](https://github.com/user-attachments/assets/5023b342-46cc-4751-9a09-28b7bb615443)

**Comment by MarcSkovMadsen** [comment]
## 6. Make Pyodide code blocks work (importShim is not defined, unsupported in polyfill mode)

When I check https://holoviz-dev.github.io/panel/reference/custom_components/AnyWidgetComponent.html, I see

![image](https://github.com/user-attachments/assets/75ddeb34-d10d-42a5-820a-2980c467a15c)

**Comment by MarcSkovMadsen** [comment]
7. Consider enabling `pn.custom.AnyWidgetComponent` usage

I was trying to simplify and align the first `AnyWidgetComponent` example with the AnyWidget docs. But I cannot fully as

```python
import panel as pn
import param

pn.extension()

class CounterButton(pn.custom.AnyWidgetComponent):
```

Yields

```bash
AttributeError: module 'panel' has no attribute 'custom'

Traceback (most recent call last):
  File "/home/jovyan/repos/private/panel/panel/io/handlers.py", line 405, in run
    exec(self._code, module.__dict__)
  File "/home/jovyan/repos/private/panel/script.py", line 6, in <module>
    class CounterButton(pn.custom.AnyWidgetComponent):
                        ^^^^^^^^^
AttributeError: module 'panel' has no attribute 'custom'
```

I'm used to always using the `pn` namespace and not seperately importing something. So I feel this is a change in the Panel way of working.

**Comment by MarcSkovMadsen** [comment]
## 8. Document how to not sync JSComponent parameters

With AnyWidget you have to actively sync paramter values between python and Javascript.

![image](https://github.com/user-attachments/assets/3bc1b5b1-d5d3-4849-af36-ce8dd1f728cb)

With Panel this is automatic. And we have to documented way to turn this of. We have seen use cases with `ReactiveHTML` where this is needed. The way to do it with `ReactiveHTML` is to set `precedence<0`. But this is a hack and we have not documented how to do this for `JSComponent` and similar.

Please find solution and document.

**Comment by MarcSkovMadsen** [comment]
## 9. Support css sharing between `AnyWidget` and `AnyWidgetComponent`

Just as sharing Javascript is a big benefit, It would be the same for css. But here the API is not the same:

- `AnyWidget` adds a class name to the `el`. This is used for css styling.

![image](https://github.com/user-attachments/assets/d97fe678-2ce6-4b00-a6ca-75dbd020310f)

The consequence is that its harder to co-develop and share widgets.

**Comment by MarcSkovMadsen** [comment]
## 10. Update `AnyWidget` *efficiency* comment.

https://holoviz-dev.github.io/panel/how_to/migrate/anywidget/index.html

![image](https://github.com/user-attachments/assets/9cb1108f-0ca6-4f1a-9392-c388a47179df)

**Comment by MarcSkovMadsen** [comment]
## 11. Review https://holoviz-dev.github.io/panel/how_to/migrate/anywidget/index.html 

Many things has changed since created. Please review the content such that its correct.

Please also consider the questions below

- Do we still want this guide?
- Should it be changed to a `AnyWidget` -> `AnyWidgetComponent` migration guide?

**Comment by MarcSkovMadsen** [comment]
## 12. Make it easy to make responsive `ReactComponent` widgets.

I've experienced several times that what is inside the `el` has a correct height and width. But the height of the `el` is smaller because it does not adjust. For example in the example below.

```python
import panel as pn
import param

from panel.custom import ReactComponent
from panel.widgets import WidgetBase

pn.extension()

class ImageButton(ReactComponent, WidgetBase):

    clicks = param.Integer(default=0)
    image = param.String()
    value = param.Event()

    _esm = """
export function render({ model }) {
    const [clicks, setClicks] = model.useState("clicks");
    const [image] = model.useState("image");

    return (
    <button onClick={e => setClicks(clicks+1)} className="pn-container center-content">
        <img src={image} className="image-size" src={ image }/>
    </button>
    )
}
"""

    _stylesheets = ["""
.pn-container {
    height: 100%;
    width: 100%;
}
.center-content {
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 1em;
}
.image-size {
    width: 100%;
    max-height: 100%;
    object-fit: contain;
}
"""]

    @param.depends('clicks')
    def _trigger_value(self):
       self.param.trigger('value')

button = ImageButton(
    image="https://panel.holoviz.org/_static/logo_stacked.png",
    styles={"border": "2px solid lightgray"},
    width=400, height=200
)
pn.Column(button, button.param.clicks).servable()
```

![image](https://github.com/user-attachments/assets/106e358a-d603-4787-96a3-ec89a5891c77)

Another example is this https://github.com/holoviz/panel/pull/7088/files#r1712966556 where a use a hack (?) which is to set the  height to the `model.height`.

**Comment by MarcSkovMadsen** [comment]
## 13. Fix document did not publish any contents

The example in https://holoviz-dev.github.io/panel/how_to/custom_components/examples/esm_leaflet.html does mark some objects `.servable()`. They are also shown. But still you can error/ warning

```python
import param
import pandas as pd
import panel as pn
import numpy as np

from panel.custom import JSComponent

class LeafletHeatMap(JSComponent):

    attribution = param.String(doc="Tile source attribution.")

    blur = param.Integer(default=18, bounds=(5, 50), doc="Amount of blur to apply to heatmap")

    center = param.XYCoordinates(default=(0, 0), doc="The center of the map.")

    data = param.DataFrame(doc="The heatmap data to plot, should have 'x', 'y' and 'value' columns.")

    tile_url = param.String(doc="Tile source URL with {x}, {y} and {z} parameter")

    min_alpha = param.Number(default=0.2, bounds=(0, 1), doc="Minimum alpha of the heatmap")

    radius = param.Integer(default=25, bounds=(5, 50), doc="The radius of heatmap values on the map")

    x = param.String(default='longitude', doc="Column in the data with longitude coordinates")

    y = param.String(default='latitude', doc="Column in the data with latitude coordinates")

    value = param.String(doc="Column in the data with the data values")

    zoom = param.Integer(default=13, bounds=(0, 21), doc="The plots zoom-level")

    _esm = """
    import L from "https://esm.sh/leaflet@1.7.1"
    import * as Lheat from "https://esm.sh/leaflet.heat@0.2.0"

    function get_records(model) {
      const records = []
      for (let i=0; i<model.data.index.length; i++)
        records.push([model.data[model.y][i], model.data[model.x][i], model.data[model.value][i]])
      return records
    }

    export function render({ model, el }) {
      const map = L.map(el).setView(model.center, model.zoom);

      map.on('change:zoom', () => { model.zoom = map.getZoom() })

      const tileLayer = L.tileLayer(model.tile_url, {
        attribution: model.attribution,
        maxZoom: 21,
        tileSize: 512,
        zoomOffset: -1,
      }).addTo(map)

      model.on("after_render", () => {
        console.log(Lheat)
        map.invalidateSize()
        const data = get_records(model)
        const heatLayer = L.heatLayer(
          data, {
            blur: model.blur,
            radius: model.radius,
            max: 10,
            minOpacity: model.min_alpha
        }).addTo(map)

        model.on(['blur', 'min_alpha', 'radius'], () => {
          heatLayer.setOptions({
            blur: model.blur,
            minOpacity: model.min_alpha,
            radius: model.radius,
          })
        })
        model.on('change:data', () => heatLayer.setLatLngs(get_records(model)))
      })
    }"""

    _stylesheets = ['https://unpkg.com/leaflet@1.7.1/dist/leaflet.css']

pn.extension(template='bootstrap')

url = "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_month.csv"

earthquakes = pd.read_csv(url)

heatmap = LeafletHeatMap(
    attribution='Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
    data=earthquakes[['longitude', 'latitude', 'mag']],
    min_height=500,
    tile_url='https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}.jpg',
    radius=30,
    sizing_mode='stretch_both',
    value='mag',
    zoom=2,
)

description=pn.pane.Markdown(f'## Earthquakes between {earthquakes.time.min()} and {earthquakes.time.max()}\n\n[Data Source]({url})', sizing_mode="stretch_width")

pn.Column(
    description,
    pn.Row(
        heatmap.controls(['blur', 'min_alpha', 'radius', 'zoom']).servable(target='sidebar'),
        heatmap.servable(),
        sizing_mode='stretch_both'
    ),
    sizing_mode='stretch_both'
)
```

![image](https://github.com/user-attachments/assets/51ce48c8-0ce3-4d20-9dd6-95e6c25e8eb8)

**Comment by MarcSkovMadsen** [comment]
## 13. Add missing styles to Material UI examples

Trying to run the example https://holoviz-dev.github.io/panel/how_to/custom_components/examples/esm_material_ui.html I can see that it does not look anything like Material UI components. They are not styled.

![image](https://github.com/user-attachments/assets/20d21353-e04f-4097-939b-b06d1dca8fb6)

**Comment by MarcSkovMadsen** [comment]
## 14. Fix errors and exceptions in docs build logs.

Looking at the logs of a docs build there are many. These should be fixed. And even better the build should fail if there are errors.

**Comment by MarcSkovMadsen** [comment]
## 15. Discrete Player broken

In `doc/how_to/param/custom.md` the example below is broken. Can't figure out why.

```python
import panel as pn
import param

pn.extension()

class CustomExample(param.Parameterized):
    """An example Parameterized class"""

    select_string = param.Selector(objects=["red", "yellow", "green"])
    autocomplete_string = param.Selector(default='', objects=["red", "yellow", "green"], check_on_set=False)
    select_number = param.Selector(objects=[0, 1, 10, 100])


pn.Param(CustomExample.param, widgets={
    'select_string': pn.widgets.RadioButtonGroup,
    'autocomplete_string': pn.widgets.AutocompleteInput,
    'select_number': pn.widgets.DiscretePlayer}
).servable()
```

![image](https://github.com/user-attachments/assets/1a4032ac-5541-44db-b405-780dda7464d4)

**Comment by MarcSkovMadsen** [comment]
16. Finalize Chat layout change

I tried out Panel 1.5.0b8 with the ChatInterface and to me the layout change seems unfinished. At least as a user I have a lot of questions.

- Why is there a green, blinking circle in the middle of nowhere?
- Why is there a vertical bar next to the copy icon?
- Why is the time and the copy icon on seperate line?

I would suggestions aligning the time, copy icon and loading circle on the same line below the chat interface. And removing the vertical bar unless something is shown on the right of it.

![image](https://github.com/user-attachments/assets/4649ac9c-4425-4768-8768-d74d33f5001c)

@ahuang11

**Comment by ahuang11** [comment]
The green circle in the middle is definitely unintended.

**Comment by philippjfr** [comment]
> The green circle in the middle is definitely unintended; it's supposed to be next to the user name.

Haven't seen that but let's fix that asap.

> The vertical line is to divide the copy icon from the reaction icons.

It shouldn't be there if there's no reaction icons though.

**Comment by ahuang11** [comment]
How do you reproduce the green circle? It seems properly positioned for me.

<img width="1428" alt="image" src="https://github.com/user-attachments/assets/30ad6105-6799-4026-b0cf-bb592d90e594">

**Comment by philippjfr** [comment]
Have you tried different browsers? I think @MarcSkovMadsen uses Edge.

**Comment by ahuang11** [comment]
On Edge
<img width="808" alt="image" src="https://github.com/user-attachments/assets/5d4da4a7-8955-4d6b-ad98-b48cbf85ecfb">

**Comment by philippjfr** [comment]
Maybe something is off with Marc's user string? Lots of spaces maybe?

**Comment by ahuang11** [comment]
I think I was able to reproduce with `pn.extension(sizing_mode="stretch_width")`; fixed it by setting `sizing_mode=None` and setting `width: fit-content` for name/activity dot

<img width="1463" alt="image" src="https://github.com/user-attachments/assets/a396084e-45d7-4997-bafa-98066fd67b14">

**Comment by MarcSkovMadsen** [comment]
## Add missing `FileDropper` thumbnail.

When building the docs I see.

Used existing FileDownload thumbnail
getting thumbnail code for /home/jovyan/repos/private/panel/examples/reference/widgets/FileDropper.ipynb
Path exists True
Traceback (most recent call last):
  File "/tmp/tmpgivt71lq", line 67, in <module>
    from nbsite.gallery.thumbnailer import thumbnail;thumbnail(file_dropper, '/home/jovyan/repos/private/panel/doc/reference/widgets/thumbnails/FileDropper')
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/repos/private/panel/.pixi/envs/docs/lib/python3.11/site-packages/nbsite/gallery/thumbnailer.py", line 133, in thumbnail
    obj.save(basename+'.png')
  File "/home/jovyan/repos/private/panel/panel/viewable.py", line 964, in save
    return save(
           ^^^^^
  File "/home/jovyan/repos/private/panel/panel/io/save.py", line 272, in save
    return save_png(
           ^^^^^^^^^
  File "/home/jovyan/repos/private/panel/panel/io/save.py", line 85, in save_png
    state.webdriver = webdriver_control.create()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/repos/private/panel/.pixi/envs/docs/lib/python3.11/site-packages/bokeh/io/webdriver.py", line 180, in create
    driver = self._create(kind, scale_factor=scale_factor)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jovyan/repos/private/panel/.pixi/envs/docs/lib/python3.11/site-packages/bokeh/io/webdriver.py", line 198, in _create
    raise RuntimeError("Neither firefox and geckodriver nor a variant of chromium browser and " \
RuntimeError: Neither firefox and geckodriver nor a variant of chromium browser and chromedriver are available on system PATH. You can install the former with 'conda install -c conda-forge firefox geckodriver'.
FileDropper thumbnail export failed

**Comment by MarcSkovMadsen** [comment]
## 18. Enable Marc to create PY.CAFE Panel user and migrate examples to that user

See https://github.com/holoviz/panel/pull/7183

**Comment by ahuang11** [comment]
Should https://github.com/holoviz/panel/pull/6819 go in for 1.5.0?

**Comment by MarcSkovMadsen** [comment]
## 19. Add missing `Placeholder` thumbnail

![image](https://github.com/user-attachments/assets/8a6dd267-2450-4401-aacb-8b9a1b7f90b7)

**Comment by MarcSkovMadsen** [comment]
20. Deprecate fastapi embed guide.

The guide at https://holoviz-dev.github.io/panel/how_to/integrations/FastAPI_Tornado.html is now superseeded by https://holoviz-dev.github.io/panel/how_to/integrations/FastAPI.html. We should delete the deprecated guide or make it very clear its deprecated.

**Comment by MarcSkovMadsen** [comment]
## 21. Update Custom Components Explanation

https://holoviz-dev.github.io/panel/explanation/components/reactive_html_components.html is marketed as custom components explanation. It no longer is a good explanation now that we have esm components.

**Comment by simontaurus** [comment]
@MarcSkovMadsen: You marked 
 6. Make Pyodide code blocks work (importShim is not defined, unsupported in polyfill mode)
 as fixed - is this fix already included in panel 1.5.5 ?

**Comment by MarcSkovMadsen** [comment]
I think someone else marked it solved. @philippjfr ?
