### ISSUE TITLE
Panel docs issues

### ISSUE THREAD

**Issue by jbednar** [holoviz/panel#794]
Comparing https://panel.pyviz.orgl/index.html and https://pyviz-dev.github.io/panel/index.html:

# home page

- [x] Thumbnails are now small and surrounded by whitespace:
![image](https://user-images.githubusercontent.com/1695496/68974977-a9f47000-07b7-11ea-842e-e5c71ac01461.png)
![image](https://user-images.githubusercontent.com/1695496/68974992-b11b7e00-07b7-11ea-9fb9-b8e285ffb154.png)

- [x] https://pyviz-dev.github.io/panel/Roadmap.html is out of date

- [x] Homepage mentions "commit" twice; seems redundant and confusing

- [x] "Panel is currently in prerelease status, which means that it is available for public use but has an API that is expected to change with each new release without detailed notice." -- Is that still true (until 1.0?)?  Maybe it can be deleted already?

- [x] The last line of the homepage should probably link to examples.pyviz.org for the other examples.

# getting_started/

- [x] Is the [announcement blog](http://blog.pyviz.org/panel_announcement.html) really the right thing to link to here?  Maybe link to that and later releases?

- [x] Actually, it doesn't work! :-) 
![image](https://user-images.githubusercontent.com/1695496/68975584-4408e800-07b9-11ea-85b7-506f4441c945.png)

- [x] Given that this is about getting started, it should have an unmissable warning that the widgets won't be live, so that people don't think it's broken. There is text, but not a big banner. I wonder if we could focus on some JS things from the very start so that they actually work.

- [x] Is Pipelines still "a work in progress"?  Not sure if we still need to warn about that, now that it has become much more fleshed out.

# user_guide/

- [x] Shouldn't there be live deployed apps somewhere? I'm not seeing any, but also not any error messages
- [x] The sidebar and user_guide/index.html should presumably be in the same order.

# Customization.html

- Shouldn't this be as wide as the screen (also wrong on the public site)?
![image](https://user-images.githubusercontent.com/1695496/68976124-af9f8500-07ba-11ea-8db8-c80dc251b133.png)

# Param.html

- [x] Shouldn't the dataframe widget have a title "dataframe", like all the others do?

# Deploy_and_Export.html

- [x] Should have clear links to "Server Deployment", as it's hard to tell which one a user needs.

# Server_Deployment.html

- [x] Shouldn't the binder section mention jupyter_panel_proxy?
- [x] The AE5 section can be very short and just point to examples.pyviz.org, saying that you just need to write an anaconda_project.yml file like any of the examples there, and the site also has some docs about how to write such projects.
- [x] Instead of having empty sections, it should probably have just one section at the end like "# Other deployment options" with "Panel can be used with just about any cloud provider that can launch a Python process, including Amazon Web Services (AWS), Google Cloud Platform (GCP), Azure, and DigitalOcean. The Panel developers will add documentation for these services as they encounter them in their own work, but we would greatly appreciate step-by-step instructions from users working on each of these systems."

# gallery/

- [ ] Shouldn't many of the demos at examples.pyviz.org be listed here under Demos?
- [x] Clifford shouldn't be in Demos; Attractors should be (as Clifford is not the "sophisticated app"; that's Attractors).
- [x] Shouldn't Vtkinteractive be under Demos? It's sophisticated and always works (as it's JS based).

# Roadmap

- [x] Roadmap is out of date

# FAQ.html

- [x] Should have another copy of the Matplotlib FAQ question right below it, answering the question for Pandas .plot specifically (as that's neither the pyplot API nor the MPL OO API).
- [x] Replace _ with * (e.g. in _designed_)
- [x] The mermaid diagram link is broken (goes to text, not SVG): https://raw.githubusercontent.com/pyviz/holoviz/b4d7516aadb7c86aa9597f775477beae3145fd72/doc/flowcharts/holoviz.mermaid.svg

# about.html

- [x] Add text from https://github.com/holoviz/geoviews/blob/master/doc/about.rst

**Comment by philippjfr** [comment]
- [ ] FileSelector does not render nicely: https://pyviz-dev.github.io/panel/reference/widgets/FileSelector.html
